version: '3'
services:
  productoschain-angular:
    container_name: productoschain-angular
    hostname: productoschain-angular
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - productoschain-net
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 80M
        reservations:
          cpus: '0.1'
          memory: 50M
networks:
  productoschain-net:
    driver: bridge